### ISSUE TITLE
Implicit hydrogen count for aromatic organic atoms is not clear

### ISSUE THREAD

**Issue by merkys** [vfscalfani/IUPAC_SMILES_plus#10]
This issue originates in the OpenSMILES specification. Section "Organic Subset" does not describe implicit hydrogen count determination for aromatic organic atoms. I think the specification should have a paragraph explaining that.

Possibly "The implicit hydrogen count is determined by summing the bond orders of the bonds connected to the atom" rule could be applied here by treating aromatic bond as of order 1.5, if only sums of 4.5 are OK for atoms in fused-ring compounds. However, I am not sure if this is correct in all situations.

**Comment by vfscalfani** [comment]
Hi, sorry for the lack of updates. We discussed this over the summer and are working on the aromaticity section revisions now. We should have a draft ready for review soon that addresses the implicit hydrogen count. I'll add your name to the pull request comments when it is ready so you can take a look. Thanks, Vin.

**Comment by merkys** [comment]
Great, thanks for the update!

**Comment by vfscalfani** [comment]
Aromaticity section has been updated with instructions for determining implicit hydrogen count. See https://github.com/IUPAC/IUPAC_SMILES_plus/pull/30
