### ISSUE TITLE
Consistency of n for atom properties

### ISSUE THREAD

**Issue by vfscalfani** [vfscalfani/IUPAC_SMILES_plus#14]
There is currently a variety of inconsistency with `n` across atom properties and rings within the specification:

Hydrogens: `Hn`, where `n` is allowed from `0` to `9`.
Charge: `+n` or `-n` where `n` is allowed from `0` to `15`
Isotopes: `n` can be `0` to `999`
Atom Class: `n` can be `0` to `9999`
Rings: `n` can be `0` to `999`. 

Note that in all cases leading zeros are not allowed such as `01`, so that part is consistent. I think it makes sense to make `n` consistent across everything. So, why not have `n` for all atom properties and rings be from `0` to `9999`?  Thoughts?

**Comment by merkys** [comment]
Personally I am fine with having "chemically-sane" limits. I do not think there is currently a need for three-digit hydrogen count, or four-digit charge and isotope number. But atom class and ring bond number indeed benefit from larger limits.

**Comment by vfscalfani** [comment]
For the consistency of n for atom properties, here is what we decided to do for now:

Hydrogens: `Hn` or `Hnn` (max 2 digits)
Charge: `+n / -n` or `+nn / -nn` (max 2 digits)
Isotopes: `nnn` (max 3 digits)
Atom Class: `nnnn`(max 4 digits)
Rings: `n`, `%nn`, `%nnn`, or `%(nnn)` notation. (max 3 digits)

In all cases, leading zeros are not allowed.
