### ISSUE TITLE
Writing preferred form is aromatic

### ISSUE THREAD

**Issue by vfscalfani** [vfscalfani/IUPAC_SMILES_plus#15]
Currently the IUPAC SMILES+ draft specification says that the aromatic SMILES form is preferred when writing SMILES. Does the community agree with this, or should it be changed to recommend writing Kekule SMILES?

**Comment by merkys** [comment]
I have used this as an argument in https://github.com/dan2097/opsin/issues/139, suggesting mode of software to produce SMILES in aromatic form. To be more specific, I am using SMILES descriptors to match molecules. Different forms of kekulisation hamper this task, whereas aromatic forms are really easy to compare.

**Comment by vfscalfani** [comment]
We have decided to recommend Kekule SMILES for sharing data; aromatic SMILES are fine for internal use.
