### ISSUE TITLE
Grammar rule for ringbond %nnn is superfluous

### ISSUE THREAD

**Issue by merkys** [vfscalfani/IUPAC_SMILES_plus#24]
PR #20 introduced ringbond rule for `%nnn` which I deem to be superfluous, and I believe formal compiler generators would think the same:
```
ringbond ::= bond? '%' digit_nonzero digit digit
```
In human readable text it is explained that `%abc` means opening/closing of two ring bonds, `ab` and `c`, and this explanation is appropriate. However, per formal grammar `%nnn` would already be understood appropriately as two ring bonds by these rules:
```
ringbond ::= bond? '%' digit_nonzero digit
ringbond ::= bond? digit
```
I suggest removing `bond? '%' digit_nonzero digit digit` from `ringbond` rule to keep the grammar simple and unambiguous.

**Comment by vfscalfani** [comment]
Thanks. We are going to go ahead and remove the `%nnn` support, in favor of `%(nnn)`. This should also help avoid ambiguity.
