### ISSUE TITLE
Rings, do not re-use numbers?

### ISSUE THREAD

**Issue by vfscalfani** [vfscalfani/IUPAC_SMILES_plus#29]
Suggestion: 

As a best practice, do not reuse ring numbers.

Prefer `c1ccccc1-c2ccccc2` instead of `c1ccccc1-c1ccccc1`

Vin

**Comment by merkys** [comment]
Reusing ring numbers helps slightly reducing overall SMILES string length, i.e., reusing `9` instead of taking `10` saves two symbols.

**Comment by vfscalfani** [comment]
Thanks @merkys. The thought was that less ambiguity is worth some additional characters. What do you think?

**Comment by merkys** [comment]
> Thanks @merkys. The thought was that less ambiguity is worth some additional characters. What do you think?

I agree, clarity is indeed worth additional symbols.
