### ISSUE TITLE
Should we remove proposed extensions from the IUPAC SMILES+ [working draft] specification?

### ISSUE THREAD

**Issue by vfscalfani** [vfscalfani/IUPAC_SMILES_plus#3]
In the current [IUPAC SMILES+ Specification [working draft]](https://github.com/vfscalfani/IUPAC_SMILES_plus/blob/master/IUPAC_SMILES%2B.asciidoc) document, there is a section on Proposed Extensions ([see Section 9](https://github.com/vfscalfani/IUPAC_SMILES_plus/blob/master/IUPAC_SMILES%2B.asciidoc#proposed-extensions)).

I recommend we remove the proposed extension section, and transfer this content to a separate document. This seems to make more sense as proposed SMILES extensions are not part of the specification. In the separate document of proposed extensions, we can also keep track of new community requests such as the recent request for a [relative chirality extension](https://sourceforge.net/p/blueobelisk/mailman/message/36670233/) proposed by Craig James.

As proposed extensions are then approved by the community (in a TBD mechanism), we can then incorporate them into the specification document. Thoughts?

**Comment by WildCation** [comment]
Makes sense to me
