### ISSUE TITLE
[new repository] Periodic table in machine readable formats

### ISSUE THREAD

**Issue by szepeviktor** [vfscalfani/IUPAC_SMILES_plus#35]
Hello!

I read IUPAC is _The world authority on chemical nomenclature_.
Do you plan to publish `IUPAC/Periodic_Table` with - for example - `periodic-table.json`?

**Comment by szepeviktor** [comment]
I see people [rely on Wikipedia](https://github.com/Bowserinator/Periodic-Table-JSON/issues/60) - which is not wise.

**Comment by vfscalfani** [comment]
Hi, thanks for your note and suggestion! For periodic table data from IUPAC, I would recommend checking out the CIAAW data: https://ciaaw.org/

I don't think CIAAW data is available in JSON data yet, however, you could take a look at the PubChem periodic table for now as they have cited a lot of CIAAW and other relevant element data. If you click on "Download" for either the entire periodic table or an individual element, you can download JSON data:

https://pubchem.ncbi.nlm.nih.gov/periodic-table/

There is an IUPAC working group for creating an IUPAC machine-readable periodic table dataset and we will hopefully make some progress on this in 2024.

Vin

**Comment by szepeviktor** [comment]
> There is an IUPAC working group for creating an IUPAC machine-readable periodic table dataset

Thank you for the good news.
