### ISSUE TITLE
Upload SMILES, IUPAC dataset.

### ISSUE THREAD

**Issue by Sulstice** [vfscalfani/IUPAC_SMILES_plus#6]
The dataset I have is massive and looks something like this below:

<img width="768" alt="Screen Shot 2020-07-31 at 10 00 35 AM" src="https://user-images.githubusercontent.com/11812946/89048037-df74c580-d314-11ea-9675-3e22c12706ae.png">

<img width="757" alt="Screen Shot 2020-07-31 at 10 02 27 AM" src="https://user-images.githubusercontent.com/11812946/89048123-fddac100-d314-11ea-9e05-3012f1086cb8.png">

As of right now the data is still being cleaned and processed but nearly ready just needs to get out there.

This should help satisfy requirements for the testing of openSMILES (perhaps)

**Comment by vfscalfani** [comment]
Great, thanks. Are these SMILES machine generated (e.g., virtually created?). As long as the dataset can be published with a permissible reuse license, we'll definitely check it out! The more SMILES we have to test, the better.

**Comment by Sulstice** [comment]
Ya! Let me go check my history of where this came from (I think it was some government chemical toxic data) -  only dataset I was able to dig up that had SMILES/Common name. Tbh, I don't know whether the SMILES was hand or machine-generated.

**Comment by vfscalfani** [comment]
okay, by virtual, I meant if you enumerated them yourself, rather than a curated list from another source. Thanks

**Comment by Sulstice** [comment]
Hey @vfscalfani, check this out and see if it fits your purposes!

https://www.kaggle.com/sulimansharif/iupacsmilesinchlkey

Just uploaded it.

**Comment by vfscalfani** [comment]
Thanks! We will take a look at this.
