### ISSUE TITLE
Integrate PRs from timvdm/OpenSMILES

### ISSUE THREAD

**Issue by merkys** [vfscalfani/IUPAC_SMILES_plus#7]
As IUPAC SMILES+ specification document seems to be a fork (not in git sense) of the one at [timvdm/OpenSMILES](https://github.com/timvdm/OpenSMILES), it would be great if IUPAC SMILES+ could integrate my tiny fixes to upstream document, namely https://github.com/timvdm/OpenSMILES/pull/6 and https://github.com/timvdm/OpenSMILES/pull/7.

**Comment by vfscalfani** [comment]
Thanks very much. I added these correction in and credited you. We will have some more major additions and clarifications to the specification coming this fall.

**Comment by merkys** [comment]
Thanks a lot!
